// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoqTestDemoApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoqTestDemoApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230619175910_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoqTestDemoApp.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 190, DateTimeKind.Utc).AddTicks(5484),
                            Email = "June.Hegmann61@yahoo.com",
                            FirstName = "June",
                            LastName = "Hegmann",
                            Phone = "1-969-838-9776 x3249"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 190, DateTimeKind.Utc).AddTicks(6434),
                            Email = "Jeremiah_Barton62@hotmail.com",
                            FirstName = "Jeremiah",
                            LastName = "Barton",
                            Phone = "(326) 780-1683 x195"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 190, DateTimeKind.Utc).AddTicks(7246),
                            Email = "Sonya_Kling10@gmail.com",
                            FirstName = "Sonya",
                            LastName = "Kling",
                            Phone = "(330) 886-2591 x049"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 190, DateTimeKind.Utc).AddTicks(8042),
                            Email = "Grant_Crona68@hotmail.com",
                            FirstName = "Grant",
                            LastName = "Crona",
                            Phone = "1-882-451-8270 x5456"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 190, DateTimeKind.Utc).AddTicks(8812),
                            Email = "Warren_Jenkins@yahoo.com",
                            FirstName = "Warren",
                            LastName = "Jenkins",
                            Phone = "648.200.9511 x2905"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 190, DateTimeKind.Utc).AddTicks(9593),
                            Email = "Maria_Ankunding60@yahoo.com",
                            FirstName = "Maria",
                            LastName = "Ankunding",
                            Phone = "1-760-858-4742"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 191, DateTimeKind.Utc).AddTicks(325),
                            Email = "Pete33@yahoo.com",
                            FirstName = "Pete",
                            LastName = "Mohr",
                            Phone = "568.849.1339 x772"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 191, DateTimeKind.Utc).AddTicks(1049),
                            Email = "Virginia39@yahoo.com",
                            FirstName = "Virginia",
                            LastName = "Wolf",
                            Phone = "1-651-747-3438 x26759"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 191, DateTimeKind.Utc).AddTicks(1820),
                            Email = "Dustin_Conn@hotmail.com",
                            FirstName = "Dustin",
                            LastName = "Conn",
                            Phone = "773.732.7535"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2023, 6, 19, 17, 59, 10, 191, DateTimeKind.Utc).AddTicks(2525),
                            Email = "Ruby.Batz14@hotmail.com",
                            FirstName = "Ruby",
                            LastName = "Batz",
                            Phone = "1-241-686-7956 x20547"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
